// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("adaptive_concurrency")
	ScopeName = "go.opentelemetry.io/collector/extension/adaptiveconcurrencyextension"
)

const (
	ExtensionStability = component.StabilityLevelAlpha
)
