// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"context"
	"errors"
	"sync"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/metric/embedded"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("go.opentelemetry.io/collector/extension/adaptiveconcurrencyextension")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("go.opentelemetry.io/collector/extension/adaptiveconcurrencyextension")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                            metric.Meter
	mu                               sync.Mutex
	registrations                    []metric.Registration
	AdaptiveConcurrencyBackoffEvents metric.Int64Counter
	AdaptiveConcurrencyFailures      metric.Int64Counter
	AdaptiveConcurrencyLimit         metric.Int64ObservableGauge
	AdaptiveConcurrencyLimitChanges  metric.Int64Counter
	AdaptiveConcurrencyPermitsInUse  metric.Int64ObservableGauge
	AdaptiveConcurrencyRtt           metric.Int64Histogram
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// RegisterAdaptiveConcurrencyLimitCallback sets callback for observable AdaptiveConcurrencyLimit metric.
func (builder *TelemetryBuilder) RegisterAdaptiveConcurrencyLimitCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.AdaptiveConcurrencyLimit, obs: o})
		return nil
	}, builder.AdaptiveConcurrencyLimit)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterAdaptiveConcurrencyPermitsInUseCallback sets callback for observable AdaptiveConcurrencyPermitsInUse metric.
func (builder *TelemetryBuilder) RegisterAdaptiveConcurrencyPermitsInUseCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.AdaptiveConcurrencyPermitsInUse, obs: o})
		return nil
	}, builder.AdaptiveConcurrencyPermitsInUse)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

type observerInt64 struct {
	embedded.Int64Observer
	inst metric.Int64Observable
	obs  metric.Observer
}

func (oi *observerInt64) Observe(value int64, opts ...metric.ObserveOption) {
	oi.obs.ObserveInt64(oi.inst, value, opts...)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.AdaptiveConcurrencyBackoffEvents, err = builder.meter.Int64Counter(
		"otelcol_adaptive_concurrency.backoff_events",
		metric.WithDescription("Number of backoff events triggered. [Development]"),
		metric.WithUnit("{events}"),
	)
	errs = errors.Join(errs, err)
	builder.AdaptiveConcurrencyFailures, err = builder.meter.Int64Counter(
		"otelcol_adaptive_concurrency.failures",
		metric.WithDescription("Number of failed requests. [Development]"),
		metric.WithUnit("{failures}"),
	)
	errs = errors.Join(errs, err)
	builder.AdaptiveConcurrencyLimit, err = builder.meter.Int64ObservableGauge(
		"otelcol_adaptive_concurrency.limit",
		metric.WithDescription("Current concurrency limit. [Development]"),
		metric.WithUnit("{permits}"),
	)
	errs = errors.Join(errs, err)
	builder.AdaptiveConcurrencyLimitChanges, err = builder.meter.Int64Counter(
		"otelcol_adaptive_concurrency.limit_changes",
		metric.WithDescription("Number of times the concurrency limit has changed. [Development]"),
		metric.WithUnit("{changes}"),
	)
	errs = errors.Join(errs, err)
	builder.AdaptiveConcurrencyPermitsInUse, err = builder.meter.Int64ObservableGauge(
		"otelcol_adaptive_concurrency.permits_in_use",
		metric.WithDescription("Number of permits currently in use. [Development]"),
		metric.WithUnit("{permits}"),
	)
	errs = errors.Join(errs, err)
	builder.AdaptiveConcurrencyRtt, err = builder.meter.Int64Histogram(
		"otelcol_adaptive_concurrency.rtt",
		metric.WithDescription("Round trip time of requests. [Development]"),
		metric.WithUnit("ms"),
		metric.WithExplicitBucketBoundaries([]float64{0, 5, 10, 25, 50, 75, 100, 250, 500, 750, 1000, 2500, 5000, 7500, 10000}...),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
